### ISSUE TITLE
Titan (and obliterator cannon) can't be built

### ISSUE THREAD

**Issue by ericcotelnu** [CaptainX3/NSC2-Development#170]
In fact, when I choose a front section, it crashes the game. It doesn't define a front or rear section at all - with a name - so when I go to choose a section type, it goes poof. Middle sections are fine.

Obliterator Cannon is also "unbuildable", sort of related to #147 .

**Comment by ericcotelnu** [comment]
I need to add more details. One, this only happens if you start off using the ”auto” one as a base. If you start from scratch, everything's fine. The other, is exactly as with #147.

**Comment by CaptainX3** [comment]
Titan is a known bug. The only fix is to make a new design. However, your version of NSC2 is somehow outdated because we changed the Titan to not make an auto-design at all in the latest version, as well as we fixed the bug with the Obliterator cannon reactor. Follow the instructions below to try to force Steam to update your copy of the mod (Multiple people have had issues in the last few days of Steam either giving them an older version or not updating properly.)

HOW TO RESET NSC2: If your copy of the mod is not working properly, delete this entire folder from your PC: Steam\SteamApps\workshop\content\281990\683230077 and then unsubscribe and resubscribe to the mod. Verify that Steam is downloading the mod, and then try to run again. **You may have to repeat this step a few times to get it working.** This is a common problem with Steam and we cannot fix it from our end.

**Comment by CaptainX3** [comment]
We've found a typo in the file for the Obliterator cannon that was causing this bug. It'll be in the next bugfix update.

**Comment by CaptainX3** [comment]
Bug fix released today in latest mod update.
